apiVersion: v1
kind: Service
metadata:
  name: {{ template "authgateway-bff.fullname" . }}-svc  
  labels:                          
    app: {{ template "authgateway-bff.name" . }}    
    chart: {{ template "authgateway-bff.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 5224
      targetPort: 5224   
      name: http       
      protocol: TCP 
  selector:
    app: {{ template "authgateway-bff.name" . }}    
    chart: {{ template "authgateway-bff.chart" . }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "authgateway-bff.fullname" . }}
  labels:
    app: {{ template "authgateway-bff.name" . }}
    chart: {{ template "authgateway-bff.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "authgateway-bff.name" . }}    
  template:
    metadata:
      labels:
        app: {{ template "authgateway-bff.name" . }}    
        chart: {{ template "authgateway-bff.chart" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OpenIdConnectOptions__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.secretName }}
                  key: {{ .Values.keycloak.clientSecretKey }}
            - name: Redis__Password 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.passwordKey }}
          envFrom:
            - configMapRef:
                name: {{ include "authgateway-bff.fullname" . }}-config
          ports:
            - containerPort: 5224
              name: http  
              protocol: TCP 
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
