config:
  openIdConnect:
    clientId: "dopamine-kick"
    redirectUri: "/dashboard"
    oidcCookieSameSite: "Lax"  # Use "Lax" for OIDC redirects to work, or "Strict" for maximum security
    cookieExpireTimeSpanHours: 8760  # 365 days

  # Reverse proxy configuration
  reverseProxy:
    routes:
      api-route:
        clusterId: "dopamine-kick-api"
        match:
          path: "/api/{**catch-all}"
    clusters:
      dopamine-kick-api:
        destinations:
          destination1:
            address: "http://dopamine-kick-api.dopamine-kick.svc.cluster.local:5009/"

keycloak:
  secretName: "keycloak-auth"
  clientSecretKey: "DOPAMINE_KICK_CLIENT_SECRET"
  serverUrl: "https://identity.alexbartleynees.com"
