config:
  openIdConnect:
    clientId: "dopamine-kick"
    redirectUri: "/dashboard"

  keycloak:
    secretName: "keycloak-auth"
    clientSecretKey: "DOPAMINE_KICK_CLIENT_SECRET"
    serverUrl: "https://identity.alexbartleynees.com"

  # Reverse proxy configuration
  reverseProxy:
    routes:
      api-route:
        clusterId: "dopamine-kick-api"
        match:
          path: "/api/{**catch-all}"
    clusters:
      dopamine-kick-api:
        destinations:
          destination1:
            address: "http://dopamine-kick-api-svc.dopamine-kick.svc.cluster.local:5185/"
